### ISSUE TITLE
Install x-small cp4waiops failed from all-in-one in new release-3.4

### ISSUE THREAD

**Issue by lihongbj** [IBM/cp4waiops-gitops#161]
Install x-small cp4waiops failed from all-in-one in new release-3.4 per doc https://github.com/IBM/cp4waiops-gitops/blob/release-3.4/docs/how-to-deploy-cp4waiops.md#option-2-experimental-install-using-all-in-one-configuration

```yaml
project: default
source:
  repoURL: 'https://github.com/IBM/cp4waiops-gitops'
  path: config/all-in-one
  targetRevision: release-3.4
  helm:
    parameters:
      - name: cp4waiops.profile
        value: x-small
      - name: cp4waiops.eventManager.enabled
        value: 'false'
destination:
  server: 'https://kubernetes.default.svc'
  namespace: openshift-gitops
syncPolicy:
  automated: {}
```

failed detail in subscription `ibm-aiops-orchestrator` :

```
Conditions:
    - lastTransitionTime: '2022-05-29T12:14:18Z'
      message: >-
        targeted catalogsource openshift-marketplace/ibm-operator-catalog
        missing
      reason: UnhealthyCatalogSourceFound
      status: 'True'
      type: CatalogSourcesUnhealthy
    - message: >-
        constraints not satisfiable: no operators found from catalog
        ibm-operator-catalog in namespace openshift-marketplace referenced by
        subscription ibm-aiops-orchestrator, subscription ibm-aiops-orchestrator
        exists
      reason: ConstraintsNotSatisfiable
      status: 'True'
      type: ResolutionFailed
```
